name: API dev destroy

on: workflow_dispatch

jobs:
  manual_destroy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: AWS cli install action
        uses: chrislennon/action-aws-cli@1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: remove roles from instance profile
        run: |
          aws iam remove-role-from-instance-profile \
            --instance-profile-name compass-instance-profile \
            --role-name compass-role

      - name: delete instance profile
        run: |
          aws iam delete-instance-profile \
            --instance-profile-name compass-instance-profile

      - name: delete policy
        run: |
          aws iam delete-role-policy \
            --role-name compass-role \
            --policy-name compass-custom-policy

      - name: detach policy AWSElasticBeanstalkWorkerTier
        run: |
          aws iam detach-role-policy \
            --role-name compass-role \
            --policy-arn "arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier"

      - name: detach policy AWSElasticBeanstalkWebTier
        run: |
          aws iam detach-role-policy \
            --role-name compass-role \
            --policy-arn "arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier"

      - name: delete role
        run: |
          aws iam delete-role \
            --role-name compass-role

      - name: terminate ElasticBeanstalk environment
        run: |
          aws elasticbeanstalk terminate-environment \
            --environment-name compassDev-env

      - name: Delete S3 bucket
        run: |
          aws s3 rb s3://compass-service-package --force

      - name: Delete ElasticBeanstalk application
        run: aws elasticbeanstalk delete-application --application-name compass-dev
