name: API prod provisioning

on: workflow_dispatch

jobs:
  manual_provisionning:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: AWS cli install action
        uses: chrislennon/action-aws-cli@1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: create role for resources accesses
        run: |
          aws iam create-role \
            --role-name compass-role \
            --assume-role-policy-document file://.github/compass-role.json
      - name: create policy to give dynamodb access to that role
        run: |
          aws iam put-role-policy \
            --role-name compass-role \
            --policy-name compass-custom-policy \
            --policy-document file://.github/compass-policies.json
      - name: attach webtier default policy
        run: |
          aws iam attach-role-policy \
            --role-name compass-role \
            --policy-arn "arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier"
      - name: attach workertier default policy
        run: |
          aws iam attach-role-policy \
            --role-name compass-role \
            --policy-arn "arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier"
      - name: create instance profile
        run: |
          aws iam create-instance-profile \
            --instance-profile-name compass-instance-profile
      - name: attach role to instance profile
        run: |
          aws iam add-role-to-instance-profile \
            --role-name compass-role \
            --instance-profile-name compass-instance-profile
      - name:
        run: aws elasticbeanstalk create-application --application-name compass-prod

      - name: Create an ElasticBeanstalk environment
        run: |
          aws elasticbeanstalk create-environment \
            --application-name compass-prod \
            --environment-name CompassProd-env \
            --cname-prefix compass-prod \
            --solution-stack-name "64bit Amazon Linux 2018.03 v2.16.4 running Docker 19.03.13-ce" \
            --option-settings file://.github/compass-provision-ebs-options.json
      - name: Create S3 Bucket for package deposit
        run: |
          aws s3api create-bucket --bucket compass-service-package-prod --region ${{ secrets.AWS_REGION }} --create-bucket-configuration LocationConstraint=${{ secrets.AWS_REGION }}
      - name: Configure access control
        run: |
          aws s3api put-public-access-block --bucket compass-service-package-prod --public-access-block-configuration "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"
