name: CI Workflow

on:
  push:
    branches-ignore:
      - dev
      - master
  workflow_dispatch:

jobs:
  front_end_tests_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Tests
        run: |
          cd ./client
          npm install
          npm run test

      - name: Build
        run: |
          cd ./client
          npm run create-dev

  backend_tests_and_bundle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: CI
        run: |
          cd ./backend
          sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
          npm install canvas
          npm install
          npm run test
