name: DynamoDB provisioning

on: workflow_dispatch

jobs:
  Provisioning-dynamodb-table:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: AWS cli install action
        uses: chrislennon/action-aws-cli@1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create Surveys table
        run: |
          aws dynamodb create-table \
              --table-name Surveys \
              --attribute-definitions \
                  AttributeName=id,AttributeType=S \
              --key-schema \
                  AttributeName=id,KeyType=HASH \
              --provisioned-throughput \
                  ReadCapacityUnits=10,WriteCapacityUnits=5
