name: E2E test

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: e2e test against dev environment
        run: |
          cd ./testE2E
          npm install
          npm run e2e-