name: Frontend dev destroy

on: workflow_dispatch

jobs:
  frontend-dev-destroy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: AWS cli install action
        uses: chrislennon/action-aws-cli@1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Delete S3 bucket
        run: |
          aws s3 rb s3://compass.dev.codurance.io --force
